### ISSUE TITLE
Shows the ignored packages

### ISSUE THREAD

**Issue by iDenso** [L11R/waybar-updates#13]
Waybar-updates worked perfectly until I added a package I wanted to ignore into `/etc/pacman.conf`.

> IgnorePkg = my-pkg
> NoUpgrade = my-pkg

It does skip it in pacman / yay but not in waybar-updates.

**Comment by L11R** [comment]
@iDenso hm, I didn't think about that. It should be relatively easy to support, but I am not sure how to reliable parse Pacman config using bash. Simple grep'ing should be enough, but I am not sure.

**Comment by L11R** [comment]
Oh, there is `pacman-conf` command. But I am not sure what param I should respect, probably `NoUpgrade`?

**Comment by iDenso** [comment]
I just checked the arch wiki page and it seems like (if I understood correctly) the `IgnorePkg` don't touch to the package at all while the `NoUpgrade` don't touch to the current version of the package but keep downloading the newer version beside.
Tbh I'm not an expert at all but if you could add at least the `IgnorePkg` it would be really great 😃

**Comment by L11R** [comment]
@iDenso should be fixed with v0.2.8!
