### ISSUE TITLE
Local issue with join

### ISSUE THREAD

**Issue by jlaunay** [L11R/waybar-updates#14]
As my locale is French (fr_FR.utf8)  I had the following error:

join: input is not in sorted order
```
join: /proc/self/fd/11:74 : n'est pas trié : gtklock-git 2.1.0.r14.g6732a03-1
join: l'entrée n'est pas dans l'ordre trié
```

To avoid any locale-related issues, it is recommended to use the 'C' locale with join [here](https://github.com/L11R/waybar-updates/blob/01b97dc0fddd0501636daf3294eb4b747618c27d/waybar-updates#L72C21-L72C21)

`aur_updates=$(LC_ALL=C join <(echo "$old_aur_packages") <(echo "$new_aur_packages")`

**Comment by L11R** [comment]
@jlaunay are you sure it related to locale? Maybe I need to sort it? French has other alphabet order?

**Comment by jlaunay** [comment]
I think so, look [here](https://www.gnu.org/software/coreutils/manual/html_node/Sorting-files-for-join.html) or [here](https://unix.stackexchange.com/questions/12942/join-file-2-not-in-sorted-order).
With `LANG=C` (or LC_ALL) or `join -i`, no more errors.

**Comment by L11R** [comment]
@jlaunay if it's not hard for you, could you manually edit /usr/bin/waybar-updates with suggested patch and test if it's works?

**Comment by jlaunay** [comment]
> @jlaunay if it's not hard for you, could you manually edit `/usr/bin/waybar-updates` with the suggested patch and test if it's works?

Done, no problems since, everything works perfectly !

**Comment by L11R** [comment]
Will merget #15 and prepare new release soon.

**Comment by L11R** [comment]
@jlaunay should be available at AUR soon, thanks for the reporting!
