### ISSUE TITLE
Missing newline before AUR updates start

### ISSUE THREAD

**Issue by zochris** [L11R/waybar-updates#9]
The first AUR package starts on the same line as the last regular package.
See attached screenshot:
![Screenshot demonstrating missing newline](https://github.com/L11R/waybar-updates/assets/20927697/95f2dfe3-a069-4145-9a52-8dc8e0491ce8)

obs-studio in this case is the first and only AUR package.

The configuration I use is the one provided in the readme.

**Comment by L11R** [comment]
@zochris should be shipped in v0.2.5 release! Thanks for the report!
